SELECT TO_DATE(TBL.BLOCK_TIMESTAMP) AS time, COUNT(TBL.BLOCK_HASH) AS value FROM OPTIMISM.CORE.FACT_TRANSACTIONS AS TBL 
  WHERE UPPER(TBL.STATUS) = 'SUCCESS'
  AND TBL.BLOCK_TIMESTAMP > DATEADD(YEAR, -1, GETDATE())
GROUP BY TO_DATE(TBL.BLOCK_TIMESTAMP)
ORDER BY TO_DATE(TBL.BLOCK_TIMESTAMP) ASC